-- S2-01: Danh mục nhà xuất bản dùng cho chức năng thêm nhanh trong form đầu sách.
-- Giữ trường books.publisher để bảo toàn API và dữ liệu lịch sử hiện tại.
CREATE TABLE library_publishers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_library_publishers_name_not_empty CHECK (LENGTH(BTRIM(name)) > 0)
);
CREATE UNIQUE INDEX ux_library_publishers_normalized_name
    ON library_publishers (LOWER(BTRIM(name)));
-- Tập hợp NXB đã có trong đầu sách, không tạo trùng khi khác hoa/thường.
INSERT INTO library_publishers (name)
SELECT MIN(BTRIM(publisher))
FROM books
WHERE publisher IS NOT NULL AND BTRIM(publisher) <> ''
GROUP BY LOWER(BTRIM(publisher))
ON CONFLICT DO NOTHING;
