// Optional browser QA. API responses below are fixtures only; never imported by the app.
const {chromium}=require(process.env.LIBRA_PLAYWRIGHT_MODULE || 'playwright');
const fs=require('node:fs');const assert=require('node:assert/strict');const path=require('node:path');const os=require('node:os');
const root=path.resolve(__dirname,'..');
const port=Number(process.env.LIBRA_QA_PORT || 5179);const base=`http://127.0.0.1:${port}`;
const out=process.env.LIBRA_QA_OUTPUT || path.join(os.tmpdir(),'libra-uiux-qa');fs.mkdirSync(out,{recursive:true});const results=[];
const books=Array.from({length:10},(_,i)=>({id:i+1,isbn:'9780000000000',title:['Lập trình căn bản','Những trang sách và cuộc sống','Tư duy thiết kế','Toán học trong đời sống','Khám phá thế giới'][i%5]+' · Kiểm thử',authorName:'Tác giả kiểm thử',authors:[],categoryId:1,categoryName:'Khoa học',categoryActive:true,publicationYear:2025-i,publisher:'NXB kiểm thử',pageCount:240,description:'Dữ liệu mô phỏng chỉ dùng kiểm thử giao diện; không được đưa vào mã ứng dụng.',copyCount:3,availableCount:i%3,coverImageUrl:i===0?'/missing-test-cover.png':null,availableCopies:[],queueCount:0,hasCopies:true}));
function session(role){return {tokenType:'Bearer',accessToken:'synthetic-ui-test-access',refreshToken:'synthetic-ui-test-refresh',accessTokenExpiresAt:new Date(Date.now()+3600000).toISOString(),refreshTokenExpiresAt:new Date(Date.now()+86400000).toISOString(),user:{id:1,fullName:'Người dùng kiểm thử',email:'ui@example.invalid',role}}}
async function auth(page,role){await page.evaluate(s=>{localStorage.setItem('libra_access_token',s.accessToken);localStorage.setItem('libra_refresh_token',s.refreshToken);localStorage.setItem('libra_access_expires_at',String(Date.parse(s.accessTokenExpiresAt)));localStorage.setItem('libra_refresh_expires_at',String(Date.parse(s.refreshTokenExpiresAt)));localStorage.setItem('libra_current_user',JSON.stringify(s.user));},session(role))}
(async()=>{const {createServer}=await import('vite');const server=await createServer({root,server:{host:'127.0.0.1',port,strictPort:true}});await server.listen();const browser=await chromium.launch({headless:true,executablePath:process.env.LIBRA_BROWSER_EXECUTABLE || undefined,args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu']});const context=await browser.newContext({viewport:{width:1440,height:1000}});const page=await context.newPage();const errors=[],requests=[];let mode='success',loginRole='READER',loginDelay=0,reserveAvailable=null,activeReservations=[];
const auditRecords=['BOOK_CATALOGED','CATEGORY_CREATED','AUTHOR_CREATED','AUTHOR_DELETED','CLOSED_DATES_BULK_CREATED'].map((action,i)=>({id:i+1,timestamp:'2026-10-10T08:00:00Z',actorId:1,actor:'Quản trị kiểm thử',actorRole:'Quản trị hệ thống',action,actionGroup:'OTHER',actionLabel:action,target:(i===0?'BOOK':i===1?'CATEGORY':i===4?'LIBRARY_CLOSED_DATE':'AUTHOR')+' #'+(9385+i),targetType:i===0?'BOOK':i===1?'CATEGORY':i===4?'Ngày đóng cửa':'AUTHOR',entityType:i===0?'BOOK':i===1?'CATEGORY':i===4?'LIBRARY_CLOSED_DATE':'AUTHOR',entityId:String(9385+i),ipAddress:'127.0.0.1',detail:action+'.'}));page.on('pageerror',e=>errors.push(e.message));
await page.route('**/api/v1/**',async r=>{const u=new URL(r.request().url()),path=u.pathname.replace('/api/v1','');requests.push({path,method:r.request().method(),query:Object.fromEntries(u.searchParams)});let data=[];let status=200;
 if(path==='/auth/login'){if(loginDelay)await new Promise(resolve=>setTimeout(resolve,loginDelay));data=session(loginRole)}
 else if(path==='/auth/refresh')data=session(loginRole);
 else if(path==='/books/public/search'){if(mode==='error'){status=503;data={message:'Không kết nối được dịch vụ kiểm thử.'}}else{if(mode==='loading')await new Promise(resolve=>setTimeout(resolve,700));const n=mode==='empty'?0:12;const p=Number(u.searchParams.get('page')||0);data={content:n?(p===0?books:books.slice(0,2).map((b,i)=>({...b,id:11+i}))):[],page:p,size:10,totalElements:n,totalPages:n?2:0,first:p===0,last:!n||p>0,sort:u.searchParams.get('sort')}}}
 else if(path==='/books/public/filters')data={categories:[{id:1,name:'Khoa học'},{id:2,name:'Văn học'}],publicationYears:[2025,2024]};
 else if(/^\/books\/public\/\d+$/.test(path))data={...(books.find(b=>b.id===Number(path.split('/').pop()))||books[0]),...(reserveAvailable===null?{}:{availableCount:reserveAvailable})};
 else if(path==='/dashboard/stats')data={totalAccounts:120,activeReaders:98,issuedLibraryCards:105,pendingReaderRequests:7};
 else if(path==='/readers/check-duplicate')data={emailExists:false};
 else if(path==='/readers/register')data={fullName:'Người dùng kiểm thử',email:'ui@example.invalid',memberCode:'BD-TEST',status:'PENDING'};
 else if(path==='/loans/return-lookup')data={status:'ON_TIME',message:'Đang trong hạn trả',copyId:4,barcode:'TEST-001',bookTitle:'Sách kiểm thử nhận trả',loanId:8,loanNumber:'PM-TEST',itemId:9,readerId:20,readerName:'Bạn đọc kiểm thử',borrowedAt:'2026-10-01T10:00:00Z',dueAt:'2026-10-20T10:00:00Z',checkedOn:'2026-10-10',overdueDays:0};
 else if(path==='/loans/return-confirmation')data={message:'Nhận trả sách thành công.',copyId:4,barcode:'TEST-001',bookTitle:'Sách kiểm thử nhận trả',loanId:8,loanNumber:'PM-TEST',itemId:9,itemStatus:'RETURNED',loanStatus:'RETURNED',copyStatus:'AVAILABLE',returnedAt:'2026-10-10T10:00:00Z',returnedById:1,returnedByName:'Người dùng kiểm thử'};
 else if(path==='/reservations/mine')data=activeReservations;
 else if(path==='/library-settings/weekly-schedule')data=Array.from({length:7},(_,i)=>({id:i+1,dayOfWeek:i+1,dayLabel:['Thứ Hai','Thứ Ba','Thứ Tư','Thứ Năm','Thứ Sáu','Thứ Bảy','Chủ Nhật'][i],open:i<6,openTime:i<6?'08:00':null,closeTime:i<6?'17:00':null,updatedAt:'2026-10-10T00:00:00Z',updatedBy:1}));
 else if(path==='/library-settings/closed-dates')data=[{id:1,closedDate:'2026-01-01',reason:'Tết Dương lịch'},{id:2,closedDate:'2026-09-02',reason:'Quốc khánh'},{id:3,closedDate:'2026-12-24',reason:'Ngày nghỉ theo lịch của thư viện — lý do dài để kiểm tra xuống dòng và vùng thao tác'}];
 else if(path==='/admin/audit-logs/filter-options')data={actors:[],actions:[{value:'LOGIN',label:'Đăng nhập'},{value:'CREATE_ACCOUNT',label:'Tạo tài khoản'}]};
 else if(path==='/admin/audit-logs')data=auditRecords;
 else if(/^\/admin\/audit-logs\/\d+$/.test(path))data=auditRecords.find(x=>x.id===Number(path.split('/').pop()));
 else if(path.includes('/loans')||path.includes('/audit')) {status=503;data={message:'Chưa cấu hình dữ liệu kiểm thử cho màn hình này.'}}
 await r.fulfill({status,contentType:'application/json',body:JSON.stringify(data)});
});
async function check(name,fn){try{await fn();results.push({name,status:'PASS'});console.log('PASS',name)}catch(e){results.push({name,status:'FAIL',error:e.message});console.log('FAIL',name,e.message.slice(0,300))}}
async function go(path){await page.goto(base+path);await page.waitForTimeout(350)}
async function overflow(){assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'whole page overflows')}
for(const width of [1440,768,390]){await page.setViewportSize({width,height:1000});for(const [path,name] of [['/','landing'],['/catalog','catalog'],['/catalog/books/1','detail'],['/login','login'],['/register','register']])await check(`${name} responsive ${width}`,async()=>{await go(path);await overflow();assert.equal(await page.getByText('Unexpected Application Error!').count(),0);await page.screenshot({animations:'disabled',path:`${out}/${name}-${width}-fixture.png`,fullPage:true})})}
await page.setViewportSize({width:1440,height:1000});
await check('hero search URL applies keyword to existing API',async()=>{await go('/');await page.getByLabel('Tên sách, tác giả hoặc ISBN').fill('Python căn bản');await page.getByRole('button',{name:'Khám phá sách'}).click();await page.waitForTimeout(300);assert.ok(page.url().includes('keyword='));assert.equal(requests.filter(r=>r.path==='/books/public/search').at(-1).query.keyword,'Python căn bản');await page.reload();await page.waitForTimeout(300);assert.equal(await page.getByLabel('Từ khóa tra cứu đầu sách').inputValue(),'Python căn bản')});
await check('sort does not apply unsubmitted filters or keyword',async()=>{await go('/catalog?keyword=Python');await page.getByLabel('Từ khóa tra cứu đầu sách').fill('UNSUBMITTED');await page.getByLabel('Thể loại',{exact:true}).selectOption('2');await page.getByLabel('Sắp xếp theo').selectOption('publicationYear');await page.waitForTimeout(300);const q=requests.filter(r=>r.path==='/books/public/search').at(-1).query;assert.equal(q.keyword,'Python');assert.ok(!q.categoryId);assert.equal(q.sort,'publicationYear')});
await check('catalog pagination appends unique books',async()=>{await go('/catalog');assert.equal(await page.locator('.book-card').count(),10);await page.getByRole('button',{name:'Hiển thị thêm'}).click();await page.waitForTimeout(200);assert.equal(await page.locator('.book-card').count(),12)});
await check('empty, loading, error and recovery are distinct',async()=>{mode='empty';await go('/catalog');assert.ok(await page.getByText('Không tìm thấy đầu sách phù hợp.').isVisible());mode='error';await go('/');assert.ok(await page.getByText('Chưa tải được tủ sách').isVisible());mode='loading';await page.getByRole('button',{name:'Thử lại',exact:true}).click();await page.getByRole('status',{name:'Đang tải đầu sách'}).waitFor({state:'visible'});await page.waitForTimeout(800);assert.equal(await page.locator('.book-card').count(),5);mode='success'});
await check('broken cover uses fallback',async()=>{await go('/catalog/books/1');assert.ok((await page.locator('article img').first().getAttribute('src')).endsWith('default-book-cover.svg'))});
await check('guest reservation returns to target; no automatic write; login duplicate blocked',async()=>{await go('/catalog/books/2');await page.getByRole('link',{name:'Đăng nhập để đặt giữ'}).click();await page.getByLabel('Email',{exact:true}).fill('ui@example.invalid');await page.getByLabel('Mật khẩu',{exact:true}).fill('test-only-value');loginDelay=250;const before=requests.filter(r=>r.path==='/auth/login').length;await page.getByRole('button',{name:'Đăng nhập',exact:true}).click();await page.locator('form').dispatchEvent('submit');await page.waitForURL('**/catalog/books/2');await page.waitForTimeout(300);assert.equal(requests.filter(r=>r.path==='/auth/login').length-before,1);assert.equal(requests.filter(r=>r.method==='POST'&&r.path.includes('/reservations')).length,0);assert.equal(await page.locator('.public-header').getByRole('link',{name:'Đăng nhập',exact:true}).count(),0);loginDelay=0});
await check('registration has generated reader code and persistent mismatch',async()=>{await go('/register');assert.equal(await page.locator('input[name="memberCode"],input[name="studentCode"],input[name="staffCode"]').count(),0);await page.getByLabel(/^Mật khẩu/).fill('abc12345');await page.getByLabel(/^Xác nhận mật khẩu/).fill('other');await page.getByLabel(/^Xác nhận mật khẩu/).blur();await page.waitForTimeout(3100);assert.ok(await page.getByText('Mật khẩu xác nhận không khớp.',{exact:true}).isVisible())});
for(const role of ['ADMIN','LIBRARY_MANAGER','LIBRARIAN','READER'])await check(`role navigation ${role}`,async()=>{await auth(page,role);await go('/dashboard');if(role==='READER'){await page.waitForURL('**/catalog');return}assert.ok(await page.getByRole('heading',{name:'Tổng quan',exact:true}).isVisible());const nav=page.locator('.desktop-sidebar');assert.equal(await nav.getByRole('link',{name:'Kho & kệ',exact:true}).count(),role==='LIBRARIAN'?0:1);assert.ok(await nav.getByRole('link',{name:'Nhận trả sách',exact:true}).isVisible())});
await auth(page,'ADMIN');
for(const width of [1440,768,390])await check(`dashboard/sidebar responsive ${width}`,async()=>{await page.setViewportSize({width,height:1000});await go('/dashboard');await overflow();await page.screenshot({animations:'disabled',path:`${out}/dashboard-${width}-fixture.png`,fullPage:true});if(width<1024){await page.getByRole('button',{name:'Mở menu điều hướng'}).click();await page.waitForTimeout(250);assert.ok(await page.getByRole('dialog').isVisible());const x=await page.getByRole('dialog').boundingBox();assert.equal(x.x,0);await page.keyboard.press('Tab');assert.ok(await page.evaluate(()=>document.querySelector('dialog').contains(document.activeElement)));await page.keyboard.press('Escape');assert.equal(await page.locator('dialog').count(),0);assert.ok(await page.getByRole('button',{name:'Mở menu điều hướng'}).evaluate(el=>el===document.activeElement))}});
await page.setViewportSize({width:1440,height:1000});
await check('sidebar collapse / groups / one active item / persistent layout',async()=>{await go('/dashboard');await page.locator('header').evaluate(el=>el.dataset.identity='keep');await page.getByRole('button',{name:'Thu gọn thanh điều hướng'}).click();await page.waitForTimeout(250);assert.equal(Math.round((await page.locator('.desktop-sidebar').boundingBox()).width),80);await page.getByRole('button',{name:'Mở rộng thanh điều hướng'}).click();await page.locator('.desktop-sidebar').getByRole('link',{name:'Tra cứu phiếu mượn',exact:true}).click();await page.waitForTimeout(300);assert.equal(await page.locator('.desktop-sidebar [aria-current="page"]').count(),1);assert.equal(await page.locator('header').getAttribute('data-identity'),'keep');await page.getByRole('button',{name:'Mượn trả',exact:true}).click();assert.equal(await page.getByRole('button',{name:'Mượn trả',exact:true}).getAttribute('aria-expanded'),'false')});
await check('return confirmation focus trap, cancellation, one write and 3-second notification',async()=>{await go('/loans/receive-return');await page.getByLabel('Mã vạch bản sao').fill('TEST-001');await page.getByRole('button',{name:'Tìm phiếu mượn'}).click();await page.getByRole('button',{name:'Xác nhận nhận trả',exact:true}).click();const dialog=page.getByRole('alertdialog');await dialog.waitFor();assert.equal(requests.filter(r=>r.path==='/loans/return-confirmation').length,0);for(let i=0;i<8;i++){await page.keyboard.press('Tab');assert.ok(await dialog.evaluate(el=>el.contains(document.activeElement)))}await page.keyboard.press('Escape');assert.equal(await dialog.count(),0);await page.getByRole('button',{name:'Xác nhận nhận trả',exact:true}).click();await page.getByRole('alertdialog').getByRole('button',{name:'Xác nhận',exact:true}).click();await page.waitForTimeout(120);assert.equal(requests.filter(r=>r.path==='/loans/return-confirmation').length,1);assert.ok(await page.locator('.feedback-alert').isVisible());await page.waitForTimeout(3050);assert.equal(await page.locator('.feedback-alert').count(),0);assert.ok(await page.getByText('Đã nhận thành công: 1 cuốn').isVisible())});
await check('legacy account modal opens, focus trapped, closes with Escape',async()=>{await go('/users');const add=page.getByRole('button',{name:/Tạo tài khoản/}).first();await add.click();await page.getByRole('dialog').waitFor();for(let i=0;i<20;i++){await page.keyboard.press(i%2?'Tab':'Shift+Tab');assert.ok(await page.getByRole('dialog').evaluate(el=>el.contains(document.activeElement)))}await page.waitForTimeout(200);await page.screenshot({animations:'disabled',path:out+'/account-modal.png'});await page.keyboard.press('Escape');assert.equal(await page.getByRole('dialog').count(),0)});
await check('reduced motion disables animations without hiding notifications',async()=>{await page.emulateMedia({reducedMotion:'reduce'});await go('/');assert.equal(await page.evaluate(()=>matchMedia('(prefers-reduced-motion: reduce)').matches),true);await page.getByRole('link',{name:'Tra cứu sách',exact:true}).first().click();assert.equal(await page.locator('.page-transition').evaluate(el=>el.getAnimations().length),0);await page.emulateMedia({reducedMotion:'no-preference'})});
await check('unknown route and direct refresh recover',async()=>{await go('/does-not-exist');assert.ok(await page.getByText('Không tìm thấy trang.').isVisible());await page.getByRole('link',{name:'Quay lại trang chủ'}).click();await page.reload();await page.waitForTimeout(250);assert.ok(await page.getByRole('heading',{name:/Khám phá tri thức/}).isVisible())});

// Regression checks for the seven issues reported after the first delivery.
for(const width of [1920,1440,768,390]) {
 await page.setViewportSize({width,height:1000});
 await check(`V2 catalog form balanced ${width}`,async()=>{await go('/catalog');await overflow();const row=await page.locator('.catalog-search-row').boundingBox(),filters=await page.locator('.catalog-filter-grid').boundingBox();assert.ok(Math.abs(row.width-filters.width)<2);assert.ok(Math.abs(row.x-filters.x)<2);await page.screenshot({animations:'disabled',path:`${out}/v2-catalog-${width}.png`,fullPage:true})});
 await auth(page,'ADMIN');
 await check(`V2 calendar actions visible without horizontal scroll ${width}`,async()=>{await go('/library-calendar');await page.getByRole('button',{name:'Chỉnh sửa ngày nghỉ',exact:true}).first().waitFor();await overflow();for(const heading of await page.locator('.calendar-panel-header h2').all()){const box=await heading.boundingBox();assert.ok(box.width>=240,'calendar heading squeezed')}for(const name of ['.closed-date-table-wrap','.weekly-schedule-table'])assert.ok(await page.locator(name).evaluate(el=>el.scrollWidth<=el.clientWidth+1),name+' overflows');for(const action of await page.getByRole('button',{name:'Xóa ngày nghỉ',exact:true}).all()){const r=await action.boundingBox();assert.ok(r.x>=0&&r.x+r.width<=width+1)}await page.screenshot({animations:'disabled',path:`${out}/v2-calendar-${width}.png`,fullPage:true});await page.getByRole('button',{name:'Chỉnh sửa ngày nghỉ',exact:true}).first().click();await page.getByRole('dialog').waitFor();await page.keyboard.press('Escape');assert.equal(await page.getByRole('dialog').count(),0)});
 await check(`V2 catalog dialogs fit ${width}`,async()=>{await go('/cataloging');await page.getByRole('button',{name:'Biên mục sách mới',exact:true}).click();let dialog=page.getByRole('dialog');await dialog.waitFor();let box=await dialog.boundingBox();assert.ok(box.width<=Math.min(width,810)&&box.width>Math.min(width-35,680));assert.ok(await dialog.evaluate(el=>el.scrollWidth<=el.clientWidth+1));await page.screenshot({animations:'disabled',path:`${out}/v2-book-modal-${width}.png`});await page.keyboard.press('Escape');await go('/authors');await page.getByRole('button',{name:'Thêm tác giả',exact:true}).click();dialog=page.getByRole('dialog');await dialog.waitFor();box=await dialog.boundingBox();assert.ok(box.width<=Math.min(width,555)&&box.width>Math.min(width-35,500));assert.ok(await dialog.evaluate(el=>el.scrollWidth<=el.clientWidth+1));await page.screenshot({animations:'disabled',path:`${out}/v2-author-modal-${width}.png`});await page.keyboard.press('Escape')});
 await check(`V2 registration placeholders and visibility toggle ${width}`,async()=>{await go('/register');for(const id of ['register-password','register-confirmPassword'])assert.ok(await page.locator('#'+id).evaluate(el=>{const style=getComputedStyle(el),ctx=document.createElement('canvas').getContext('2d');ctx.font=style.font;return ctx.measureText(el.placeholder).width<=el.clientWidth-parseFloat(style.paddingLeft)-parseFloat(style.paddingRight)}),'placeholder clipped: '+id);await page.locator('#register-password').fill('UiExample123');await page.getByRole('button',{name:'Hiện mật khẩu',exact:true}).click();assert.equal(await page.locator('#register-password').getAttribute('type'),'text');assert.equal(await page.locator('#register-password').inputValue(),'UiExample123');await page.getByRole('button',{name:'Ẩn mật khẩu',exact:true}).click();assert.equal(await page.locator('#register-password').getAttribute('type'),'password');await page.screenshot({animations:'disabled',path:`${out}/v2-register-${width}.png`,fullPage:true})});
}
await page.setViewportSize({width:1440,height:1000});
await check('V2 reservation plus uses real availability and remaining slots',async()=>{await auth(page,'READER');reserveAvailable=1;activeReservations=[{id:1,status:'PENDING'}];await go('/catalog/books/2');assert.ok(await page.getByRole('button',{name:'Tăng số lượng',exact:true}).isDisabled());assert.ok(await page.getByText('Không thể tăng thêm: đầu sách hiện chỉ có 1 bản sẵn sàng.',{exact:true}).isVisible());reserveAvailable=3;await go('/catalog/books/2');assert.ok(await page.getByRole('button',{name:'Tăng số lượng',exact:true}).isEnabled());await page.getByRole('button',{name:'Tăng số lượng',exact:true}).click();assert.equal(await page.locator('#reserve-book-title').locator('..').locator('output').innerText(),'2');assert.ok(await page.getByRole('button',{name:'Tăng số lượng',exact:true}).isDisabled());assert.ok(await page.getByText(/Không thể tăng thêm: bạn chỉ còn 2 lượt/).isVisible());await page.getByRole('button',{name:'Giảm số lượng',exact:true}).click();assert.equal(await page.locator('#reserve-book-title').locator('..').locator('output').innerText(),'1');activeReservations=Array.from({length:3},(_,i)=>({id:i,status:'PENDING'}));await go('/catalog/books/2');assert.ok(await page.getByRole('button',{name:'Tăng số lượng',exact:true}).isDisabled());assert.ok(await page.getByRole('button',{name:'Đặt giữ 1 bản',exact:true}).isDisabled());reserveAvailable=0;activeReservations=[];await go('/catalog/books/2');assert.equal(await page.getByRole('button',{name:'Tăng số lượng',exact:true}).count(),0);assert.ok(await page.getByRole('button',{name:'Đặt giữ vào hàng đợi',exact:true}).isEnabled());reserveAvailable=null;activeReservations=[]});
await check('V2 audit Vietnamese labels retain IDs, raw codes and filter values',async()=>{await auth(page,'ADMIN');await go('/audit-log');for(const label of ['Biên mục đầu sách','Thêm thể loại','Thêm tác giả','Xóa tác giả','Thêm nhiều ngày nghỉ'])assert.ok(await page.locator('tbody').getByText(label,{exact:true}).isVisible());assert.ok(await page.getByText('Đầu sách #9385',{exact:true}).isVisible());await page.getByRole('button',{name:'Xem chi tiết',exact:true}).first().click();await page.getByRole('dialog').waitFor();assert.ok(await page.getByRole('dialog').getByText('Biên mục đầu sách',{exact:true}).isVisible());assert.ok(await page.getByRole('dialog').getByText('BOOK_CATALOGED',{exact:true}).isVisible());await page.keyboard.press('Escape');await page.screenshot({animations:'disabled',path:`${out}/v2-audit.png`,fullPage:true});const action=page.locator('select').filter({has:page.locator('option[value="LOGIN"]')});await action.selectOption('LOGIN');await page.locator('form button[type="submit"]').click();await page.waitForTimeout(250);assert.equal(requests.filter(r=>r.path==='/admin/audit-logs').at(-1).query.action,'LOGIN')});
await check('V2 login has home link without redundant catalog link',async()=>{await go('/login');assert.equal(await page.getByText('Tra cứu đầu sách công khai',{exact:true}).count(),0);assert.ok(await page.getByRole('link',{name:'← Về trang chủ LIBRA',exact:true}).isVisible())});

await check('no runtime errors',async()=>assert.deepEqual(errors,[]));
fs.writeFileSync(out+'/browser-results.json',JSON.stringify({results,errors},null,2));await browser.close();await server.close();if(results.some(r=>r.status==='FAIL'))process.exitCode=1;
})().catch(e=>{console.error(e);process.exit(1)})
